
sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: 8.5.0
branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
script:
  - npm run validate
after_success:
  - npm run report-coverage
  - npm run release